apiVersion: extensions/v1beta1
kind: Ingress
metadata:
 name: path-ingress
spec:
  tls:
    - hosts:
   {{ if eq .Release.Namespace "dev" }}
      - dev.uday.com
   {{ end }}
      secretName: uday-com-secret
  rules:
{{ if eq .Release.Namespace "dev" }}
  - host: dev.uday.com
{{ end }}
    http:
      {{- if .Values.pathsmap }}
      {{ .Values.pathsmap | toYaml | trimPrefix "|-\n" | nindent 4}}
      {{- end }}
